# Generated by Django 4.2.3 on 2023-07-12 11:20

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='ChargerItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Модель товару',
            },
        ),
        migrations.CreateModel(
            name='ChargersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=40, populate_from='title', unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('small_description', models.TextField(max_length=100, verbose_name='Короткий опис')),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
                ('power', models.IntegerField(verbose_name='Потужність, кВт')),
                ('power_amps', models.IntegerField(verbose_name='Потужність, А')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name="Тип роз'єму")),
                ('cable_length', models.IntegerField(verbose_name='Довжина кабелю')),
                ('protection', models.CharField(max_length=10, verbose_name='Захист корпусу')),
                ('guarantee', models.CharField(max_length=10, verbose_name='Гарантія')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('country', models.CharField(max_length=20, verbose_name='Країна-виробник')),
                ('form', models.CharField(max_length=15, verbose_name='Формфактор')),
                ('features', models.TextField(max_length=200, verbose_name='Додаткові функції')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Зображення')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.chargeritemmodel')),
            ],
        ),
    ]
